# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
source:           ./docs
destination:      ./_gh_pages
host:             0.0.0.0
port:             9002
baseurl:          /
url:              http://localhost:9002

# Custom vars
current_version:  3.1.0-3.1.0
repo:             https://github.com/todc/todc-bootstrap

download:
  source:         https://github.com/todc/todc-bootstrap/archive/v3.1.0-3.1.0.zip
  dist:           https://github.com/todc/todc-bootstrap/releases/download/v3.1.0-3.1.0/todc-bootstrap-3.1.0-3.1.0-dist.zip

bs_repo:          https://github.com/twbs/bootstrap

bs_download:
  source:         https://github.com/twbs/bootstrap/archive/v3.1.0.zip
  dist:           https://github.com/twbs/bootstrap/releases/download/v3.1.0/bootstrap-3.1.0-dist.zip

bs_docs:          http://getbootstrap.com
blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com

cdn:
  css:            //netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css
  css_theme:      //netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css
  js:             //netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js
