# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9002
baseurl:          /
url:              http://todc.github.io/todc-bootstrap
encoding:         UTF-8

# Custom vars
current_version:  3.1.1-3.2.1
repo:             https://github.com/todc/todc-bootstrap

download:
  source:         https://github.com/todc/todc-bootstrap/archive/v3.1.1-3.2.1.zip
  dist:           https://github.com/todc/todc-bootstrap/releases/download/v3.1.1-3.2.1/todc-bootstrap-3.1.1-3.2.1-dist.zip

bs:
  current_version:  3.1.1
  repo:             https://github.com/twbs/bootstrap
  download:
    source:         https://github.com/twbs/bootstrap/archive/v3.1.1.zip
    dist:           https://github.com/twbs/bootstrap/releases/download/v3.1.1/bootstrap-3.1.1-dist.zip
    sass:           https://github.com/twbs/bootstrap-sass/archive/v3.1.1.tar.gz
  blog:             http://blog.getbootstrap.com
  expo:             http://expo.getbootstrap.com
  docs:             http://getbootstrap.com

sass_repo:        https://github.com/twbs/bootstrap-sass


cdn:
  css:            //netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css
  css_theme:      //netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css
  css_rtl:        //netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-rtl.min.css
  js:             //netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js
