# Dependencies
markdown:     rdiscount
pygments:     true

# Permalinks
permalink:    pretty

# Server
destination:  ./_gh_pages
exclude:      [".editorconfig", ".gitignore", ".ruby-version", "bower.json", "composer.json", "CONTRIBUTING.md", "LICENSE", "Makefile", "package.json", "node_modules", "README.md", "codekit-config.json", "*.TODO"]
port:         9002
baseurl:      ""    # for local dev
# baseurl:      /todc-bootstrap-3   # GitHub repository
