# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
destination:      ./_gh_pages
exclude:          [".editorconfig", ".gitignore", ".ruby-version", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less", "bootstrap", "codekit-config.json", "*.TODO"]
port:             9002

# Custom vars
repo:                       https://github.com/todc/todc-bootstrap
download:                   https://github.com/todc/todc-bootstrap/archive/3.0.0-wip.zip
download_dist:              https://github.com/todc/todc-bootstrap/releases/download/v3.0.0-rc1/todc-bs-v3.0.0-rc1-dist.zip

bootstrap_repo:             https://github.com/twbs/bootstrap
bootstrap_download:         https://github.com/twbs/bootstrap/archive/3.0.0-wip.zip
bootstrap_download_dist:    http://getbootstrap.com/bs-v3.0.0-rc1-dist.zip

examples:                   http://examples.getbootstrap.com
examples_repo:              https://github.com/twbs/bootstrap-examples

glyphicons:                 http://glyphicons.getbootstrap.com
glyphicons_repo:            https://github.com/twbs/bootstrap-glyphicons

blog:                       http://blog.getbootstrap.com
expo:                       http://expo.getbootstrap.com

cdn_css:                    //netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/css/bootstrap.min.css
cdn_js:                     //netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/js/bootstrap.min.js
