# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
destination:      ./_gh_pages
port:             9002
exclude:
- ".editorconfig"
- ".gitignore"
- "*.TODO"
- "bootstrap"
- "bower.json"
- "CNAME"
- "codekit-config.json"
- "composer.json"
- "CONTRIBUTING.md"
- "DOCS-LICENSE"
- "Gruntfile.js"
- "less"
- "LICENSE"
- "node_modules"
- "package.json"
- "README.md"
- "sauce_browsers.yml"
- "test-infra"

# Custom vars
current_version:      3.1.0-3.1.0
repo:                 https://github.com/todc/todc-bootstrap

download_source:      https://github.com/todc/todc-bootstrap/archive/v3.1.0-3.1.0.zip
download_dist:        https://github.com/todc/todc-bootstrap/releases/download/v3.1.0-3.1.0/todc-bootstrap-3.1.0-3.1.0-dist.zip

bs_repo:              https://github.com/twbs/bootstrap
bs_download_source:   https://github.com/twbs/bootstrap/archive/v3.1.0.zip
bs_download_dist:     https://github.com/twbs/bootstrap/releases/download/v3.1.0/bootstrap-3.1.0-dist.zip

bs_docs:              http://getbootstrap.com
blog:                 http://blog.getbootstrap.com
expo:                 http://expo.getbootstrap.com

cdn_css:              //netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css
cdn_theme_css:        //netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css
cdn_js:               //netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js
